export const colors = {
    primaryBackground: 'blanchedAlmond',
    shadowColor: 'saddleBrown',
    shadowBorderColor: 'sienna',
    modalBackground: 'rgba(0, 0, 0, 0.5)',
    modalContentBackground: 'white',
    modalCloseButtonBackground: 'peru',
    modalCloseButtonColor: 'white',
    modalText:'maroon',
    likeIconColor: 'maroon',
    cartIconColor: 'blue',
    newBadgeBackground: 'red',
    newBadgeText: 'white',
    textColor: 'gray',
    oldPriceColor: 'red',
    newPriceColor: 'green',
};