

export const mockItemData = [
    {
      id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
      title: 'Pepperoni',
      isNew: true,
      image: require('../images/homeScreen/pepperoni.jpg'),
      oldPrice: '$14.99',
      newPrice: '$9.99',
      size42:'$12.99',
      description: 'Classic pizza with mozzarella and pepperoni sausage.',
      selectedSize: 32,
    },
    {
      id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
      title: 'Mozzarella pizza',
      isNew: false,
      image:require('../images/homeScreen/pizza-margarita.jpg'),
      oldPrice: '$12.99',
      newPrice: '$8.99',
      description: 'Delicious pizza with Italian mozzarella. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      size42:'$10.99',
      selectedSize: 32,
    },
  
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d72',
      title: 'Vegetarian pizza ',
      isNew: true,
      image:require('../images/homeScreen/pizza-vegetarian.jpg'),
      oldPrice: '$15.99',
      newPrice: '$10.99',
      size42:'$12.99',
      selectedSize: 32,
      description: 'Italian vegetarian pizza with tomatoes, mushrooms, peppers, onion, and black olives. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d73',
      title: 'Salami pizza ',
      isNew: true,
      image:require('../images/homeScreen/pizza-Salami.jpg'),
      oldPrice: '$11.99',
      newPrice: '$9.99',
      size42:'$11.99',
      selectedSize: 32,
      description: 'Italian pizza with tomato base, salami, tomato, mozzarella, garlic sauce, oregano. ',
    },
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d74',
      title: 'Napoletana ',
      isNew: false,
      image:require('../images/homeScreen/pizza-Neopolitana.jpg'),
      oldPrice: '$13.99',
      newPrice: '$10.99',
      size42:'$11.99',
      selectedSize: 32,
      description: 'Italian pizza with with tomatoes, mozzarella, mushrooms, ham, oregano. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d82',
      title: 'Seafood pizza ',
      isNew: false,
      image:require('../images/homeScreen/seafood-pizza.jpg'),
      oldPrice: '$19.99',
      newPrice: '$17.99',
      size42:'$19.99',
      selectedSize: 32,
      description: 'Italian pizza with mozzarella, salmon, mussels, calamari, tomato, lemon, pesto sauce, oregano, tomato sauce.',
    },
  
    {
      id: '58694a0f-3da1-471f-bd96-145571e29d35',
      title: 'Smoked salmon ',
      isNew: true,
      image:require('../images/homeScreen/pizza-smoked-salmon.jpg'),
      oldPrice: '$18.99',
      newPrice: '$16.99',
      size42:'$18.99',
      selectedSize: 32,
      description: 'Italian pizza with pesto sauce, smoked salmon and mozzarella cheese.',
    },
  
    {
      id: 'bd7acbea-c2b2-46c2-aed5-3ad53abb28ba',
      title: 'Hawaiian pizza ',
      isNew: false,
      image:require('../images/homeScreen/hawaiian-pizza.jpg'),
      oldPrice: '$15.99',
      newPrice: '$10.99',
      size42:'$12.99',
      selectedSize: 32,
      description: 'Italian pizza with pizza sauce, chicken, pineapple, tomato, hollandaise cheese, mozzarella cheese.',
    },
    {
      id: 'bd7acbea-c1b1-46c2-aed5-5ad53abb2836',
      title: '4 seasons pizza ',
      isNew: false,
      image:require('../images/homeScreen/pizza-fourseason.jpg'),
      oldPrice: '$16.99',
      newPrice: '$13.99',
      size42:'$15.99',
      selectedSize: 32,
      description: 'Italian pizza with special sauce, mozzarella cheese, pepperoni, olives, ham, mushrooms, bell peppers, onions, oregano.',
    },
    {
      id: '58694a0f-3da1-471f-bd96-135571e29d25',
      title: '4 cheeses pizza ',
      isNew: false,
      image:require('../images/homeScreen/pizza-fourchees.jpg'),
      oldPrice: '$18.99',
      newPrice: '$16.99',
      size42:'$18.99',
      selectedSize: 32,
      description: 'Italian pizza with blue or mature cheese, soft (emmental or gruyere) or cream cheese (robiola or stracchino) and hard cheese (parmesan or pecorino, grated).',
    },
  
  
];


export const mockOnEndReachedData = [
 {
   id: '58694a0f-3da1-471f-bd96-146932e29d94',
   title: 'Сaesar pizza ',
   isNew: true,
   image: require('../images/homeScreen/pizza-сaesar.jpg'),
   oldPrice: '$15.99',
   newPrice: '$12.99',
   size42:'$14.99',
   selectedSize: 32,
   description: 'Italian pizza with chicken breast, mozzarella cheese, parmesan cheese, quail eggs, tomatoes, iceberg lettuce, provan herbs, béchamel sauce.',
  },
  {
    id: '58694a0f-3da1-471f-bd96-146971e29d25',
    title: 'Margarita ',
    isNew: false,
    image: require('../images/homeScreen/pizza-margarita.jpg'),
    oldPrice: '$14.99',
    newPrice: '$11.99',
    size42:'$13.99',
    selectedSize: 32,
    description: 'Italian pizza with mozzarella cheese, tomatoes and tomato sauce.',
  },
  {
    id: '58694a0f-3da1-471f-bd25-12571e45d36',
    title: 'BBQ Pizza ',
    isNew: true,
    image: require('../images/homeScreen/pizza-bbq.jpg'),
    oldPrice: '$16.99',
    newPrice: '$13.99',
    size42:'$15.99',
    selectedSize: 32,
    description: 'Italian pizza with BBQ sauce,mozzarella cheese,prosciutto,bacon,game sausages,fried mushrooms,pickled cucumber,olives,greens.',
  },

  {
    id: '58294a0f-5da1-221f-bd26-148961e29p46',
    title: 'Very cheesy Pizza ',
    isNew: false,
    image: require('../images/homeScreen/pizza-5syrov.jpg'),
    oldPrice: '$19.99',
    newPrice: '$17.99',
    size42:'$19.99',
    selectedSize: 32,
    description: 'Italian pizza with mozzarella cheese, parmesan cheese, Dor Blue cheese, cheddar cheese slice, feta cheese, cream sauce.',
  },

  {
    id: '5825a0f-3da5-471f-bd25-185571e29d63',
    title: 'Pesto pizza ',
    isNew: true,
    image: require('../images/homeScreen/pizza-pesto.jpg'),
    oldPrice: '$14.99',
    newPrice: '$12.99',
    size42:'$14.99',
    selectedSize: 32,
    description: 'Italian pizza with parmesan cheese, pine nuts, garlic, green basil, tomatoes, cheese, pesto sauce.',
  },


]
